######################################################################
# Automatically generated by qmake (2.01a) Di. Okt 6 11:47:42 2009
######################################################################

TEMPLATE 	= subdirs
TARGET 		= 
SUBDIRS	 	+= listfile dummy mapping

