######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 23 08:58:59 2014
######################################################################

VERSION		= 1.0.0
SRCBASE		= ../..
include($${SRCBASE}/mesydaqconfig.pri)

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += . ../../qmesydaq

# Input

FORMS	= ../../qmesydaq/ipaddresswidget.ui

HEADERS = ../../qmesydaq/ipaddresswidget.h

SOURCES = main.cpp \
	  ../../qmesydaq/ipaddresswidget.cpp

