######################################################################
# Automatically generated by qmake (2.01a) Fr. Jun 15 14:19:02 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
	plot.cpp \
	mainwindow.cpp

HEADERS += data.h \
	plot.h \
	mainwindow.h

INCLUDEPATH += /usr/local/qwt5/include
DEPENDPATH += /usr/local/qwt5/include

LIBS	+= -L /usr/local/qwt5/lib/ -lqwt
