######################################################################
# Automatically generated by qmake (2.01a) Di. Okt 6 09:55:57 2009
######################################################################

TEMPLATE 	= app
TARGET 		= listfile
DEPENDPATH 	+= . ../../lib
INCLUDEPATH 	+= . ../../lib

QT		+= core network

CONFIG		+= debug

# Input
SOURCES 	+= main.cpp

LIBS        	+= -L../../lib -lmesydaq
