######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 14 15:35:51 2012
######################################################################

TEMPLATE 	= app
TARGET 		= 
DEPENDPATH 	+= .
INCLUDEPATH 	+= .

# Input
HEADERS 	+= diskspace.h
SOURCES 	+= main.cpp

LIBS 		+= -lboost_filesystem -lboost_system

INSTALLS 	=
