######################################################################
# Automatically generated by qmake (2.01a) Mo. Okt 5 11:04:42 2009
######################################################################

TEMPLATE 	= app
TARGET 		= qmsetip

QT		+= core network

CONFIG		+= debug

DEPENDPATH 	+= ../../lib .
INCLUDEPATH 	+= ../../lib .

# Input
SOURCES 	+= main.cpp

LIBS        	+= -L../../lib -lmesydaq
