######################################################################
# Automatically generated by qmake (2.01a) Di. Okt 6 09:55:57 2009
######################################################################

TEMPLATE 	= app
TARGET 		= fill
DEPENDPATH 	+= . ../../lib
INCLUDEPATH 	+= . ../../lib

QT		+= core network

CONFIG		+= debug # release

# Input
SOURCES 	+= main.cpp \
		../../lib/histogram.cpp

HEADERS		+= hist.h

LIBS        	+= -L../../lib -lmesydaq
