######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 11 16:18:29 2014
######################################################################

TEMPLATE =	subdirs
CONFIG +=	ordered debug_and_release
DEPENDPATH +=	src plugin example
INCLUDEPATH +=	src plugin example

greaterThan(QT_MAJOR_VERSION, 4) {
SUBDIRS =	src example
} else {
SUBDIRS =	src plugin example
}
