######################################################################
# Automatically generated by qmake (2.01a) Mo. Okt 5 11:04:42 2009
######################################################################

VERSION		= 1.0.2
SRCBASE		= ../..

include($${SRCBASE}/mesydaqconfig.pri)

TEMPLATE 	= app
TARGET 		= qmlsmod

QT		+= core network

CONFIG		+= debug

DEPENDPATH 	+= .
INCLUDEPATH 	+= .

# Input
SOURCES 	+= main.cpp

INSTALLS        = target

target.path     = $${TARGETPATH}/bin
